version: "3.3"
services:

  faiss-cpu:
    image: lifefilm/faiss-server:${TAG-latest}'
#    env_file:
#      - .env
    volumes:
      - ./resources:/opt/faiss-web-service/resources
      - /tmp:/tmp
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    command: python /opt/faiss-web-service/src/app.py
