version: "3.3"
services:

  faiss-cpu:
    image: lifefilm/faiss-server:latest
#    env_file:
#      - .env
    volumes:
      - ./resources:/app/resources
      - /tmp:/tmp
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    command: python /app/src/app.py
